# CMake generated Testfile for 
# Source directory: /home/lj/Degen-LIO/tools/pcl_point_to_plane
# Build directory: /home/lj/Degen-LIO/build/pcl_point_to_plane
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(pcl_v2_nondegenerate_identity "/home/lj/.local/share/degen-lio-micromamba/envs/degen-lio-pcl-backend/bin/python3.14" "/home/lj/Degen-LIO/tools/pcl_point_to_plane/verify_pcl_backend_v2.py" "--cli" "/home/lj/Degen-LIO/build/pcl_point_to_plane/pcl_point_to_plane_cli" "--config" "/home/lj/Degen-LIO/tools/pcl_point_to_plane/../../tests/data/pcl_backend_v2/nondegenerate_identity_config.json" "--test" "NONDEGENERATE_IDENTITY" "--output" "/home/lj/Degen-LIO/build/pcl_point_to_plane/pcl_backend_v2_results/nondegenerate_identity.json")
set_tests_properties(pcl_v2_nondegenerate_identity PROPERTIES  LABELS "pcl_backend_qualification_v2" _BACKTRACE_TRIPLES "/home/lj/Degen-LIO/tools/pcl_point_to_plane/CMakeLists.txt;27;add_test;/home/lj/Degen-LIO/tools/pcl_point_to_plane/CMakeLists.txt;0;")
add_test(pcl_v2_known_small_transform "/home/lj/.local/share/degen-lio-micromamba/envs/degen-lio-pcl-backend/bin/python3.14" "/home/lj/Degen-LIO/tools/pcl_point_to_plane/verify_pcl_backend_v2.py" "--cli" "/home/lj/Degen-LIO/build/pcl_point_to_plane/pcl_point_to_plane_cli" "--config" "/home/lj/Degen-LIO/tools/pcl_point_to_plane/../../tests/data/pcl_backend_v2/known_small_transform_config.json" "--test" "KNOWN_SMALL_TRANSFORM" "--truth" "/home/lj/Degen-LIO/tools/pcl_point_to_plane/../../tests/data/pcl_backend_v2/known_small_transform_truth.json" "--output" "/home/lj/Degen-LIO/build/pcl_point_to_plane/pcl_backend_v2_results/known_small_transform.json")
set_tests_properties(pcl_v2_known_small_transform PROPERTIES  LABELS "pcl_backend_qualification_v2" _BACKTRACE_TRIPLES "/home/lj/Degen-LIO/tools/pcl_point_to_plane/CMakeLists.txt;37;add_test;/home/lj/Degen-LIO/tools/pcl_point_to_plane/CMakeLists.txt;0;")
add_test(pcl_v2_planar_degeneracy_diagnostic "/home/lj/.local/share/degen-lio-micromamba/envs/degen-lio-pcl-backend/bin/python3.14" "/home/lj/Degen-LIO/tools/pcl_point_to_plane/verify_pcl_backend_v2.py" "--cli" "/home/lj/Degen-LIO/build/pcl_point_to_plane/pcl_point_to_plane_cli" "--config" "/home/lj/Degen-LIO/tools/pcl_point_to_plane/../../tests/data/pcl_backend_v2/planar_degeneracy_config.json" "--test" "PLANAR_DEGENERACY_DIAGNOSTIC" "--output" "/home/lj/Degen-LIO/build/pcl_point_to_plane/pcl_backend_v2_results/planar_degeneracy_diagnostic.json")
set_tests_properties(pcl_v2_planar_degeneracy_diagnostic PROPERTIES  LABELS "pcl_backend_qualification_v2" _BACKTRACE_TRIPLES "/home/lj/Degen-LIO/tools/pcl_point_to_plane/CMakeLists.txt;47;add_test;/home/lj/Degen-LIO/tools/pcl_point_to_plane/CMakeLists.txt;0;")
